import logging
import os
import pandas as pd
from datetime import datetime


from backend.mcp_data.connectors.database_connection import get_engine
from backend.mcp_data.processors.signal_repository import save_signals

from backend.Stock_Filter.pipelines.prediction.predict_model_1 import predict_model_1
from backend.Stock_Filter.pipelines.prediction.predict_model_2 import predict_model_2

logger = logging.getLogger(__name__)

def run_signal_service():
    """Execute all prediction pipelines, consolidate and output buy signals."""
    logger.info("Starting Daily Stock Prediction Service...")
    
    # Run Model 1
    logger.info("Running Model 1 (BCD Model) prediction...")
    df_signals_1 = predict_model_1()
    
    # Run Model 2
    logger.info("Running Model 2 (Breakout/SEPA Model) prediction...")
    df_signals_2 = predict_model_2()
    
    all_signals = []
    
    if not df_signals_1.empty:
        logger.info(f"Model 1 generated {len(df_signals_1)} signals.")
        all_signals.append(df_signals_1)
    else:
        logger.info("Model 1 did not generate any signals.")
        
    if not df_signals_2.empty:
        logger.info(f"Model 2 generated {len(df_signals_2)} signals.")
        all_signals.append(df_signals_2)
    else:
        logger.info("Model 2 did not generate any signals.")
        
    if all_signals:
        df_all = pd.concat(all_signals, ignore_index=True)
        # Sort by probability descending
        df_all = df_all.sort_values(by="probability", ascending=False).reset_index(drop=True)
        
        # Format dates to string
        df_all["ngay"] = pd.to_datetime(df_all["ngay"]).dt.date

        engine = get_engine()

        save_signals(
            engine=engine,
            df_signals=df_all
        )

        logger.info(
            f"Saved {len(df_all)} signals into database."
        )
        
        # output_file = "daily_signals.csv"
        # df_all.to_csv(output_file, index=False)
        # logger.info(f"Consolidated signals saved to {output_file}:")
        print("\n=== CONSOLIDATED DAILY SIGNALS ===")
        print(df_all.to_string())
        print("===================================\n")
        return df_all
    else:
        logger.info("No stock signals generated by any model today.")
        print("\n=== NO CONSOLIDATED SIGNALS TODAY ===\n")
        return pd.DataFrame()

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
    run_signal_service()
